# site settings
url: "https://bweston6.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/UoL" # the subpath of your site, e.g. /blog
title: UoL CS Notes
description: Notes for computer science modules at the University of Liverpool.
tagline: Computer science notes for University of Liverpool
locale: en_GB

author:
  name: Ben Weston
  github: bweston6
  email: b.weston60@gmail.com

github:
  repo: bweston6/UoL
  repo_tree: main/docs

plugins:
  - jekyll-seo-tag
  - rouge

# markdown options
markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# default layouts
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: default
  - 
    scope:
      path: ""
      type: pages
    values:
      layout: default

# home page options
paginate: 10
