# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          rm -rf docs/COMP*/*/_posts/*
          rm -rf docs/assets/COMP*/*/*
          mkdir -p docs/COMP105/Lectures/_posts
          mkdir -p docs/assets/COMP105/Lectures
          cp -r COMP105/Lectures/*/*.md docs/COMP105/Lectures/_posts
          cp -r COMP105/Lectures/*/* docs/assets/COMP105/Lectures
          rm -rf docs/assets/COMP105/Lectures/*.md
          mkdir -p docs/COMP107/Lectures/_posts
          mkdir -p docs/assets/COMP107/Lectures
          cp -r COMP107/Lectures/*/*.md docs/COMP107/Lectures/_posts
          cp -r COMP107/Lectures/*/* docs/assets/COMP107/Lectures
          rm -rf docs/assets/COMP107/Lectures/*.md
          mkdir -p docs/COMP107/Seminars/_posts
          mkdir -p docs/assets/COMP107/Seminars
          cp -r COMP107/Seminars/*/*.md docs/COMP107/Seminars/_posts
          cp -r COMP107/Seminars/*/* docs/assets/COMP107/Seminars
          rm -rf docs/assets/COMP107/Seminars/*.md
          mkdir -p docs/COMP107/Tutorials/_posts
          mkdir -p docs/assets/COMP107/Tutorials
          cp -r COMP107/Tutorials/*/*.md docs/COMP107/Tutorials/_posts
          cp -r COMP107/Tutorials/*/* docs/assets/COMP107/Tutorials
          rm -rf docs/assets/COMP107/Tutorials/*.md
          mkdir -p docs/COMP109/Lectures/_posts
          mkdir -p docs/assets/COMP109/Lectures
          cp -r COMP109/Lectures/*/*.md docs/COMP109/Lectures/_posts
          cp -r COMP109/Lectures/*/* docs/assets/COMP109/Lectures
          rm -rf docs/assets/COMP109/Lectures/*.md
          mkdir -p docs/COMP109/Catch-up\ Sessions/_posts
          mkdir -p docs/assets/COMP109/Catch-up\ Sessions
          cp -r COMP109/Catch-up\ Sessions/*/*.md docs/COMP109/Catch-up\ Sessions/_posts
          cp -r COMP109/Catch-up\ Sessions/*/* docs/assets/COMP109/Catch-up\ Sessions
          rm -rf docs/assets/COMP109/Catch-up\ Sessions/*.md
          mkdir -p docs/COMP109/Tutorials/_posts
          mkdir -p docs/assets/COMP109/Tutorials
          cp -r COMP109/Tutorials/*/*.md docs/COMP109/Tutorials/_posts
          cp -r COMP109/Tutorials/*/* docs/assets/COMP109/Tutorials
          rm -rf docs/assets/COMP109/Tutorials/*.md
          mkdir -p docs/COMP111/Lectures/_posts
          mkdir -p docs/assets/COMP111/Lectures
          cp -r COMP111/Lectures/*/*.md docs/COMP111/Lectures/_posts
          cp -r COMP111/Lectures/*/* docs/assets/COMP111/Lectures
          rm -rf docs/assets/COMP111/Lectures/*.md
          mkdir -p docs/COMP111/Tutorials/_posts
          mkdir -p docs/assets/COMP111/Tutorials
          cp -r COMP111/Tutorials/*/*.md docs/COMP111/Tutorials/_posts
          cp -r COMP111/Tutorials/*/* docs/assets/COMP111/Tutorials
          rm -rf docs/assets/COMP111/Tutorials/*.md
          mkdir -p docs/COMP107/Assessments/_posts
          mkdir -p docs/assets/COMP107/Assessments
          cp -r COMP107/Assessments/*/*/*.md docs/COMP107/Assessments/_posts
          cp -r COMP107/Assessments/*/*/* docs/assets/COMP107/Assessments
          rm -rf docs/assets/COMP107/Assessments/*.md
          grep -rliF ' $ ' docs/COMP*/*/* | xargs -i@ sed -i 's/ \$ /??????/g' @
          grep -rliF '$$' docs/COMP*/*/* | xargs -i@ sed -i 's/_/\&#95;/g' @
          grep -rliF '$' docs/COMP*/*/* | xargs -i@ docs/tools/debuck @
          rm -rf docs/COMP*/*/_posts/*.bak
          grep -rliF '\' docs/COMP*/*/* | xargs -i@ sed -i 's/\\(/\&#92;(/g; s/\\)/\&#92;)/g; s/\\\[/\&#92;\[/g; s/\\\]/\&#92;\]/g; s/\\{/\&#92;{/g; s/\\}/\&#92;}/g; s/\\\\/\&#92;\&#92;/g; s/\\\$/\&#92;\$/g' @
          grep -rliF '??????' docs/COMP*/*/* | xargs -i@ sed -i 's/??????/ \$ /g' @
          git config user.name bweston6
          git config user.email 35574350+bweston6@users.noreply.github.com
          git add .
          git commit -m "Copying site assets."
          git push
